SELECT *
FROM BRIGHT_COFFEE_DATA_SET;



-- revenue per transaction
SELECT TRANSACTION_ID,
TRANSACTION_QTY*UNIT_PRICE AS REVENUE 
FROM BRIGHT_COFFEE_DATA_SET;

--we counting the number of transaction
SELECT COUNT(TRANSACTION_ID)
AS NUMBER_OF_TRANSACTION 
FROM BRIGHT_COFFEE_DATA_SET;

--count the number of shop
SELECT COUNT(DISTINCT STORE_ID)
AS NUMBER_OF_SHOP
FROM BRIGHT_COFFEE_DATA_SET;

--show us the name of the different store location
SELECT DISTINCT STORE_LOCATION,
STORE_ID
FROM BRIGHT_COFFEE_DATA_SET;

--calculate the revenue per store location
SELECT STORE_LOCATION,
SUM(TRANSACTION_QTY*UNIT_PRICE)
AS REVENUE
FROM BRIGHT_COFFEE_DATA_SET
GROUP BY STORE_LOCATION;

--THE CLOSING TIME OF THE SHOP
SELECT MAX(TRANSACTION_TIME)
AS CLOSING_TIME
FROM BRIGHT_COFFEE_DATA_SET;

--CHECKING THE FIRST_OPERATION_HOURS
SELECT MIN(TRANSACTION_TIME) 
AS OPENING_TIME
FROM BRIGHT_COFFEE_DATA_SET;

--CHECKING THE LAST DATE OPERATION
SELECT MAX(TRANSACTION_DATE)
AS LAST_DATE_OPERATION
FROM BRIGHT_COFFEE_DATA_SET;

--CHECKING THE FIRST DATE OPERATION
SELECT MIN(TRANSACTION_DATE)
AS FIRST_DATE_OPERATION
FROM BRIGHT_COFFEE_DATA_SET;

SELECT PRODUCT_ID,
COUNT(DISTINCT TRANSACTION_ID)AS NUMBER_OF_SALES,
PRODUCT_CATEGORY,
TRANSACTION_DATE,
DAYNAME(TRANSACTION_DATE) AS DAYNAME,
TRANSACTION_TIME,
HOUR(TRANSACTION_TIME) AS HOUR,
SUM(TRANSACTION_QTY*UNIT_PRICE)
AS REVENUE,
STORE_LOCATION,
TRANSACTION_DATE,
TRANSACTION_TIME,
CASE WHEN DAYNAME(TRANSACTION_DATE) IN ('SAT,SUN') THEN 'WEEKEND'
ELSE 'WEEKDAY'
END AS DAY_CLASSIFICATION,
MONTHNAME(TRANSACTION_DATE) AS MONTH_NAME,
CASE WHEN TRANSACTION_TIME BETWEEN'06:00:00' AND'11:59:59' THEN '01,MORNING'
WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '15:59:59' THEN '02,AFTERNOON'
WHEN TRANSACTION_TIME BETWEEN '16:00:00'AND '20:00:00' THEN '03,EVENING'
WHEN TRANSACTION_TIME >='20:00:00' THEN '04,NIGHT' 
END AS TIME_BUCKET 
FROM BRIGHT_COFFEE_DATA_SET
GROUP BY ALL;


